# Main params
NUM_CLASSES: 5
BATCH_SIZE: 50
K_NEIGHBORS: 3
USE_BIAS: True
#TODO remote config overwrite from main cfg (low priority)
#Model skeleton
TOPOLOGY: [ 'BACKBONE_2D', 'DT' ] # listing here includes module (BACKBONE & KNN are enforced)

BACKBONE_2D:
  NAME: DN4_CNN2d # DN4_CNN2d | ResNet2d
  MODE: TEST
  NORM: batch
  CUDA: True
  ONE_HOT: False
  LEARNING_RATE: 0.005
  BETA_ONE: [ 0.5,0.9 ]
  INIT_WEIGHTS: kaiming

DT:
  NAME: RandomForest # XGB | RF
  MODE: TRAIN
  CUDA: True
  EPISODE_TRAIN_NUM: 6000
  PARAMETERS: { } # add parameters here to override default settings


AUGMENTOR:
  TRANSFORMS: [
    {
      NAME: Resize,
      ARGS:  [[ 84,84 ]],
      ENABLE: True,
    },
#    { NAME: RandomCrop,
#      ARGS: [84] ,
#      ENABLE: False
#    },
#    { NAME: ColorJitter,
#      ARGS: { brightness: 0.4, contrast: 0.4, saturation: 0.4 },
#      ENABLE: False
#    },
#    { NAME: RandomHorizontalFlip,
#      ARGS: [ ],
#      ENABLE: False
#    }
  ]


#BACKBONE & ENCODER

#Decision Tree
DATASET: tree_dataset_W5_S5_2023_02_22_16_00_09.csv


# Dataloader
DATASET_DIR: '../dataset/miniImageNet/'
DATA_NAME: 'miniImageNet'
OUTF: '../results/'
BASEMODEL: 'Conv64F'
WORKERS: 8
IMAGE_SIZE: 84
EPISODE_SIZE: 1
TEST_EPISODE_SIZE: 1
EPOCHS: 30
EPISODE_TRAIN_NUM: 10000
EPISODE_VAL_NUM: 600
EPISODE_TEST_NUM: 1000
WAY_NUM: 5
SHOT_NUM: 5
QUERY_NUM: 10

# Misc
PRINT_FREQ: 100