INPUT_CHANNELS: [64] #??
LAYER_NUMS: [4]
LAYER_STRIDES: [1]
LAYER_POOLS: [1]
LAYER_PADDINGS: [1]
NUM_FILTERS: [64]
MOMENTUM: 0.001

UPSAMPLE_STRIDES: 1  # []
NUM_UPSAMPLE_FILTERS: 1  # []

ACTIVATION: Relu
NORMALIZATION: BatchNorm2d
POOLING: MaxPool2d

NORM_ARGS: 1 # for now only one set of parameters
POOL_ARGS: 1
DEBLOCK_ARGS: 1
FILE_TYPE: YAML