TYPE: CLASSIFIER # REGRESSOR | CLASSIFIER

SAVE_MODEL: True
MODEL_NAME: model_test
LOAD_MODEL: False

PARAMETERS: {
  tree_method: gpu_hist,
  objective: 'multi:softprob',
  eval_metric: 'auc',
  enable_categorical: True,
  max_depth: 13,
  min_child_weight: 0.5,
  gamma: 0.5,
  eta: 0.01,
  learning_rate: 0.05,
  subsample: 1,
  seed: 666,
  lambda: 0.1,
  n_estimators: 1000,
  early_stopping_rounds: 50,
  colsample_bytree: 0.9
}