TYPE: CLASSIFIER # REGRESSOR | CLASSIFIER

SAVE_MODEL: False
MODEL_NAME: model
LOAD_MODEL: True

PARAMETERS: {
  tree_method: hist,
  objective: 'reg:absoluteerror',
  enable_categorical: False,
  max_depth: 18,
  min_child_weight: 0.1,
  gamma: 0.1,
  eta: 0.01,
  learning_rate: 0.05,
  subsample: 0.95,
  seed: 666,
  lambda: 0.1,
  n_estimators: 500,
  early_stopping_rounds: 20,
  colsample_bytree: 0.9
}