# Main params
NAME: DN4
K_NEIGHBORS: 3
USE_BIAS: True
DATASET: miniImageNet
EPOCHS: 30
#Model skeleton
TOPOLOGY: { # mapping = K (interface forced module IDs) : V (your own checkpoint modules IDs)
  BACKBONE: 'BACKBONE_2D',
}
TRACK_LOSS: BACKBONE
TRACK_CRITERION: BACKBONE

BACKBONE:
  NAME: DN4_CNN2d # DN4_CNN2d | ResNet2d
  MODE: TRAIN
  GRAD: True
  NORM: batch
  CUDA: True
  LEARNING_RATE: 0.001
  BETA_ONE: [ 0.5,0.9 ]
  INIT_WEIGHTS: normal
  FREEZE_EPOCH: 1

AUGMENTOR:
  DISABLE: [ ]
  AV_NUM: 2 # number of augmented views
  AUG_NUM:  3 # number of randomly selected augmentations per view
  STRATEGY: 'N:1'
  RANDOM_AUGMENT: True # whether to use random combinations of augmentations
  PRE_PROCESS: [
    {
      NAME: RESIZE,
      ARGS: { size: [ 84,84 ] },
    }]
  AUGMENTATION:
    [
      { NAME: RANDOM_CROP,
        ARGS: [ 84 ]
      },
      { NAME: COLOR_JITTER,
        ARGS: { brightness: 0.4, contrast: 0.4, saturation: 0.4 },
      },
      { NAME: RANDOM_HORIZONTAL_FLIP,
        ARGS: [ ],
      },
    ]
  POST_PROCESS: [
    {
      NAME: RESIZE,
      ARGS: { size: [ 84,84 ] },
    },
    {
      NAME: TO_TENSOR,
      ARGS: [ ],
    },
    {
      NAME: NORMALIZE,
      ARGS: { mean: [ 0.5, 0.5, 0.5 ], std: [ 0.5, 0.5, 0.5 ] },
    }
  ]


# Dataloader
OUTF: '../results/'
WORKERS: 8
EPISODE_SIZE: 1
TEST_EPISODE_SIZE: 1

EPISODE_TRAIN_NUM: 10000
EPISODE_VAL_NUM: 800
EPISODE_TEST_NUM: 800
WAY_NUM: 5
SHOT_NUM: 1
QUERY_NUM: 15

# Misc
PRINT_FREQ: 100
