TYPE: CLASSIFIER # REGRESSOR | CLASSIFIER
#TODO update this
MODEL_NAME: model_test
OPTIMIZE: True
ENGINE: TREE
PARAMETERS: {
  tree_method: gpu_hist,
  objective: 'multi:softmax',
  eval_metric: 'mlogloss',
  max_depth: 11,
  min_child_weight: 3,
  learning_rate: 0.04,
  subsample: 0.8,
  seed: 666,
  lambda: 1,
}
