TYPE: CLASSIFIER # REGRESSOR | CLASSIFIER
MODEL_NAME: __ignore__
OPTIMIZE: True
ENGINE: TREE
GRAD: False

PARAMETERS: {
  tree_method: gpu_hist,
  objective: 'multi:softmax',
  eval_metric: 'mlogloss',
  max_depth: 11,
  min_child_weight: 3,
  learning_rate: 0.04,
  subsample: 0.8,
  seed: 666,
  lambda: 1,
}
