# Main params
NUM_CLASSES: 5
BATCH_SIZE: 75
K_NEIGHBORS: 3

#Model skeleton
BACKBONE_2D: DN4_CNN2d # DN4_CNN2d | ResNet2d
ENCODER: DN
KNN: KNN_itc
DT: XGB # XGB | RF


#BACKBONE & ENCODER
LEARNING_RATE: 0.04
BETA_ONE: 1
#Decision Tree
DATASET:


# Dataloader
DATASET_DIR: '/Datasets/miniImageNet/'
DATA_NAME: 'miniImageNet'
OUTF: './results/DN4'
BASEMODEL: 'Conv64F'
WORKERS: 8
IMAGE_SIZE: 84
EPISODE_SIZE: 1
TEST_EPISODE_SIZE: 1
EPOCHS: 30
EPISODE_TRAIN_NUM: 100
EPISODE_VAL_NUM: 1000
EPISODE_TEST_NUM: 1000
WAY_NUM: 5
SHOT_NUM: 5
QUERY_NUM: 15

# Misc
PRINT_FREQ: 100