# Main params
NUM_CLASSES: 5
BATCH_SIZE: 75
K_NEIGHBORS: 3
USE_BIAS: True
#TODO remote config overwrite from main cfg
#Model skeleton
TOPOLOGY: ['BACKBONE_2D', 'ENCODER', 'KNN', 'DT'] # listing here includes module (BACKBONE & KNN are enforced)
BACKBONE_2D:
  NAME: DN4_CNN2d # DN4_CNN2d | ResNet2d
  MODE: EVAL
  NORM: batch
ENCODER:
  NAME: DN
  MODE: TRAIN
  NORM: batch
KNN:
  NAME: KNN_itc
  MODE: None
DT:
  NAME: XGB # XGB | RF
  MODE: TRAIN


#BACKBONE & ENCODER
LEARNING_RATE: 0.04
BETA_ONE: 1
#Decision Tree
DATASET:


# Dataloader
DATASET_DIR: '/Datasets/miniImageNet/'
DATA_NAME: 'miniImageNet'
OUTF: './results/DN4'
BASEMODEL: 'Conv64F'
WORKERS: 8
IMAGE_SIZE: 84
EPISODE_SIZE: 1
TEST_EPISODE_SIZE: 1
EPOCHS: 30
EPISODE_TRAIN_NUM: 100
EPISODE_VAL_NUM: 1000
EPISODE_TEST_NUM: 1000
WAY_NUM: 5
SHOT_NUM: 5
QUERY_NUM: 15

# Misc
PRINT_FREQ: 100